"""DOCX exporter for collaborative governance risk reports."""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any

from dra_ma.reporting.word_docx_skill import WordDocxSkillGuide


RISK_LABELS = {
    "high": "高风险",
    "medium": "中风险",
    "low": "低风险",
    "insufficient_evidence": "证据不足",
}

URGENCY_LABELS = {
    "urgent": "紧急",
    "normal": "一般",
    "low": "低",
}


class DocxExporter:
    """Generate a real .docx report with the WindEye governance template."""

    def __init__(self, skill: WordDocxSkillGuide | None = None) -> None:
        self.skill = skill or WordDocxSkillGuide.load()

    def export(self, report: dict[str, Any], metadata: dict[str, Any] | None = None) -> bytes:
        try:
            from docx import Document
            from docx.enum.section import WD_SECTION
            from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml import OxmlElement
            from docx.oxml.ns import qn
            from docx.shared import Inches, Pt, RGBColor
        except ImportError as exc:
            raise RuntimeError("python-docx is required for DOCX export") from exc

        metadata = metadata or {}
        report_id = _clean_text(metadata.get("report_id") or report.get("report_id") or _make_report_id())
        query = _clean_text(metadata.get("query_text") or report.get("query_summary") or "-")
        generated_at = _clean_text(metadata.get("generated_at") or report.get("generated_at") or _now())

        doc = Document()
        section = doc.sections[0]
        section.page_width = Inches(8.27)
        section.page_height = Inches(11.69)
        section.top_margin = Inches(0.78)
        section.bottom_margin = Inches(0.72)
        section.left_margin = Inches(0.78)
        section.right_margin = Inches(0.78)

        self._configure_styles(doc)
        doc.core_properties.title = "WindEye 协同治理报告"
        doc.core_properties.subject = report_id
        doc.core_properties.comments = (
            f"Generated by WindEye DocxExporter using skill "
            f"{self.skill.slug}@{self.skill.version}: {self.skill.path}"
        )

        self._add_header_footer(doc, report_id)

        title = doc.add_paragraph(style="WindEyeTitle")
        title.alignment = WD_ALIGN_PARAGRAPH.LEFT
        title.add_run("WindEye 协同治理报告")

        subtitle = doc.add_paragraph(style="WindEyeSubtitle")
        subtitle.add_run(f"报告编号：{report_id}    生成时间：{generated_at}")

        self._add_meta_table(doc, [
            ("查询主题", query),
            ("风险等级", RISK_LABELS.get(str(report.get("overall_risk_level", "")), str(report.get("overall_risk_level", "-")))),
            ("图谱规模", _subgraph_summary(report)),
            ("技能规范", f"{self.skill.name} / {self.skill.slug}@{self.skill.version}"),
        ])

        self._add_section(doc, "一、执行摘要")
        self._add_paragraph(doc, report.get("executive_summary") or _extract_first_paragraph(report.get("markdown_report", "")))

        self._add_section(doc, "二、综合风险评分")
        self._add_score_table(doc, report.get("risk_scores") or {})

        self._add_section(doc, "三、风险传导路径")
        self._add_risk_path_table(doc, report.get("risk_paths") or [])

        self._add_section(doc, "四、异常发现")
        self._add_anomaly_table(doc, report.get("anomaly_findings") or [])

        self._add_section(doc, "五、合规匹配")
        self._add_compliance_table(doc, report.get("compliance_matches") or [])

        governance = report.get("governance_plan") or {}
        self._add_section(doc, "六、协同治理方案")
        self._add_governance(doc, governance, report.get("recommendations") or [])

        evidence = report.get("evidence_chains") or {}
        if evidence.get("chains"):
            self._add_section(doc, "七、证据链附录")
            self._add_evidence_table(doc, evidence.get("chains") or [])

        markdown_report = report.get("integrated_report") or report.get("markdown_report")
        if markdown_report:
            doc.add_section(WD_SECTION.NEW_PAGE)
            self._add_section(doc, "附录：原始报告文本")
            self._add_markdown_summary(doc, markdown_report)

        output = io.BytesIO()
        doc.save(output)
        return output.getvalue()

    def _configure_styles(self, doc: Any) -> None:
        from docx.enum.style import WD_STYLE_TYPE
        from docx.oxml.ns import qn
        from docx.shared import Pt, RGBColor

        styles = doc.styles
        normal = styles["Normal"]
        normal.font.name = "Microsoft YaHei"
        normal._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        normal.font.size = Pt(10.5)

        for name, size, color, bold, before, after in [
            ("WindEyeTitle", 22, "1f2937", True, 0, 8),
            ("WindEyeSubtitle", 10, "64748b", False, 0, 14),
            ("WindEyeHeading1", 15, "1f2937", True, 12, 8),
            ("WindEyeBody", 10.5, "334155", False, 0, 8),
            ("WindEyeCaption", 9, "64748b", False, 2, 6),
        ]:
            style = styles[name] if name in styles else styles.add_style(name, WD_STYLE_TYPE.PARAGRAPH)
            style.font.name = "Microsoft YaHei"
            style._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
            style.font.size = Pt(size)
            style.font.color.rgb = RGBColor.from_string(color)
            style.font.bold = bold
            style.paragraph_format.space_before = Pt(before)
            style.paragraph_format.space_after = Pt(after)
            style.paragraph_format.line_spacing = 1.35

    def _add_header_footer(self, doc: Any, report_id: str) -> None:
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Pt

        section = doc.sections[0]
        header = section.header.paragraphs[0]
        header.text = f"WindEye 协同治理报告 | {report_id}"
        header.style = doc.styles["WindEyeCaption"]

        footer = section.footer.paragraphs[0]
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run("WindEye 资本市场风险传导与协同治理平台")
        run.font.size = Pt(8)

    def _add_meta_table(self, doc: Any, rows: list[tuple[str, str]]) -> None:
        table = doc.add_table(rows=0, cols=2)
        self._format_table(table, [1600, 7200])
        for label, value in rows:
            cells = table.add_row().cells
            self._shade_cell(cells[0], "f1f5f9")
            self._set_cell_text(cells[0], label, bold=True)
            self._set_cell_text(cells[1], value)

    def _add_section(self, doc: Any, title: str) -> None:
        doc.add_paragraph(title, style="WindEyeHeading1")

    def _add_paragraph(self, doc: Any, text: Any) -> None:
        text = _clean_text(text) or "暂无。"
        for part in _split_paragraphs(text):
            doc.add_paragraph(part, style="WindEyeBody")

    def _add_score_table(self, doc: Any, scores: dict[str, Any]) -> None:
        rows = [
            ["基础分", _fmt_score(scores.get("base_overall"))],
            ["最终分", _fmt_score(scores.get("final_overall") or scores.get("overall"))],
            ["风险等级", RISK_LABELS.get(str(scores.get("level", "")), str(scores.get("level", "-")))],
            ["LLM 调整", _fmt_score(scores.get("llm_adjustment"))],
            ["调整原因", _clean_text(scores.get("llm_adjustment_reason") or "-")],
        ]
        self._simple_table(doc, ["指标", "值"], rows, [1800, 7000])

        details = scores.get("scores") or []
        if details:
            doc.add_paragraph("评分维度明细", style="WindEyeCaption")
            detail_rows = [
                [
                    _clean_text(item.get("dimension")),
                    _fmt_score(item.get("score")),
                    f"{item.get('weight', '')}%",
                    _clean_text(item.get("explanation") or "-"),
                ]
                for item in details
            ]
            self._simple_table(doc, ["维度", "得分", "权重", "说明"], detail_rows, [2100, 1200, 1000, 4500])

    def _add_risk_path_table(self, doc: Any, paths: list[dict[str, Any]]) -> None:
        if not paths:
            self._add_paragraph(doc, "未发现明确风险传导路径。")
            return

        rows = []
        for idx, path in enumerate(paths, 1):
            rows.append([
                str(idx),
                RISK_LABELS.get(str(path.get("risk_level", "")), str(path.get("risk_level", ""))),
                _clean_text(path.get("path_text") or path.get("path_description") or path.get("description")),
                ", ".join(_clean_text(e) for e in path.get("affected_entities", [])[:6]) or "-",
            ])
        self._simple_table(doc, ["序号", "等级", "路径说明", "涉及主体"], rows, [700, 1000, 4700, 2400])

    def _add_anomaly_table(self, doc: Any, anomalies: list[dict[str, Any]]) -> None:
        if not anomalies:
            self._add_paragraph(doc, "未发现明确异常模式。")
            return

        rows = [
            [
                str(idx),
                _clean_text(item.get("anomaly_type")),
                _clean_text(item.get("evidence")),
                _fmt_percent(item.get("confidence")),
            ]
            for idx, item in enumerate(anomalies, 1)
        ]
        self._simple_table(doc, ["序号", "异常类型", "证据", "置信度"], rows, [700, 1700, 5200, 1200])

    def _add_compliance_table(self, doc: Any, matches: list[dict[str, Any]]) -> None:
        if not matches:
            self._add_paragraph(doc, "未匹配到明确合规条款。")
            return

        rows = []
        for idx, item in enumerate(matches, 1):
            rows.append([
                str(idx),
                _clean_text(item.get("regulation")),
                _clean_text(item.get("article")),
                _clean_text(item.get("violation")),
                _clean_text(item.get("suggested_action")),
            ])
        self._simple_table(doc, ["序号", "法规", "条款", "风险点", "建议"], rows, [650, 1600, 2300, 2700, 1550])

    def _add_governance(self, doc: Any, plan: dict[str, Any], recommendations: list[dict[str, Any]]) -> None:
        actions = plan.get("actions") or []
        if actions:
            rows = [
                [
                    str(idx),
                    _clean_text(item.get("target")),
                    _clean_text(item.get("risk_issue")),
                    _clean_text(item.get("measure")),
                    URGENCY_LABELS.get(str(item.get("priority", "")), str(item.get("priority", ""))),
                    _clean_text(item.get("department")),
                ]
                for idx, item in enumerate(actions, 1)
            ]
            self._simple_table(doc, ["序号", "对象", "问题", "治理措施", "优先级", "部门"], rows, [650, 1350, 2100, 3200, 900, 1100])
        elif recommendations:
            rows = [
                [
                    str(idx),
                    _clean_text(item.get("action")),
                    _clean_text(item.get("reasoning")),
                    URGENCY_LABELS.get(str(item.get("urgency", "")), str(item.get("urgency", ""))),
                    _clean_text(item.get("department")),
                ]
                for idx, item in enumerate(recommendations, 1)
            ]
            self._simple_table(doc, ["序号", "建议", "原因", "紧急度", "部门"], rows, [700, 2300, 3500, 1000, 1300])
        else:
            self._add_paragraph(doc, "暂无治理方案。")

        rules = plan.get("escalation_rules") or []
        if rules:
            doc.add_paragraph("升级规则", style="WindEyeCaption")
            rows = [
                [_clean_text(item.get("condition")), _clean_text(item.get("action")), _clean_text(item.get("timeline"))]
                for item in rules
            ]
            self._simple_table(doc, ["触发条件", "动作", "时限"], rows, [3400, 3600, 1800])

        checklist = plan.get("monitoring_checklist") or []
        if checklist:
            doc.add_paragraph("监控清单", style="WindEyeCaption")
            for item in checklist:
                doc.add_paragraph(_clean_text(item), style="List Bullet")

    def _add_evidence_table(self, doc: Any, chains: list[dict[str, Any]]) -> None:
        rows = [
            [
                str(idx),
                _clean_text(item.get("claim")),
                _fmt_percent(item.get("confidence")),
            ]
            for idx, item in enumerate(chains[:12], 1)
        ]
        self._simple_table(doc, ["序号", "证据主张", "置信度"], rows, [700, 6800, 1300])

    def _add_markdown_summary(self, doc: Any, markdown: str) -> None:
        for raw in _split_paragraphs(markdown)[:80]:
            line = raw.strip()
            if not line:
                continue
            if line.startswith("### "):
                doc.add_paragraph(line[4:], style="WindEyeCaption")
            elif line.startswith("## "):
                doc.add_paragraph(line[3:], style="WindEyeHeading1")
            elif line.startswith("# "):
                continue
            elif line.startswith("- "):
                doc.add_paragraph(_strip_markdown(line[2:]), style="List Bullet")
            else:
                doc.add_paragraph(_strip_markdown(line), style="WindEyeBody")

    def _simple_table(self, doc: Any, headers: list[str], rows: list[list[str]], widths: list[int]) -> Any:
        table = doc.add_table(rows=1, cols=len(headers))
        self._format_table(table, widths)
        for idx, header in enumerate(headers):
            self._shade_cell(table.rows[0].cells[idx], "e2e8f0")
            self._set_cell_text(table.rows[0].cells[idx], header, bold=True)
        for row in rows:
            cells = table.add_row().cells
            for idx, value in enumerate(row):
                self._set_cell_text(cells[idx], value)
        return table

    def _format_table(self, table: Any, widths: list[int]) -> None:
        from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.LEFT
        table.autofit = False

        tbl = table._tbl
        tbl_pr = tbl.tblPr
        tbl_w = tbl_pr.find(qn("w:tblW"))
        if tbl_w is None:
            tbl_w = OxmlElement("w:tblW")
            tbl_pr.append(tbl_w)
        tbl_w.set(qn("w:type"), "dxa")
        tbl_w.set(qn("w:w"), str(sum(widths)))

        grid = tbl.tblGrid
        for child in list(grid):
            grid.remove(child)
        for width in widths:
            col = OxmlElement("w:gridCol")
            col.set(qn("w:w"), str(width))
            grid.append(col)

        for row in table.rows:
            for idx, cell in enumerate(row.cells):
                cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
                tc_pr = cell._tc.get_or_add_tcPr()
                tc_w = tc_pr.find(qn("w:tcW"))
                if tc_w is None:
                    tc_w = OxmlElement("w:tcW")
                    tc_pr.append(tc_w)
                tc_w.set(qn("w:type"), "dxa")
                tc_w.set(qn("w:w"), str(widths[min(idx, len(widths) - 1)]))
                self._set_cell_margins(cell, top=90, start=120, bottom=90, end=120)

    def _set_cell_text(self, cell: Any, text: Any, bold: bool = False) -> None:
        from docx.shared import Pt

        cell.text = ""
        paragraph = cell.paragraphs[0]
        paragraph.style = "WindEyeBody"
        paragraph.paragraph_format.space_after = Pt(0)
        run = paragraph.add_run(_clean_text(text))
        run.bold = bold
        run.font.size = Pt(9)

    def _shade_cell(self, cell: Any, fill: str) -> None:
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        tc_pr = cell._tc.get_or_add_tcPr()
        shd = tc_pr.find(qn("w:shd"))
        if shd is None:
            shd = OxmlElement("w:shd")
            tc_pr.append(shd)
        shd.set(qn("w:fill"), fill)

    def _set_cell_margins(self, cell: Any, **margins: int) -> None:
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        tc = cell._tc
        tc_pr = tc.get_or_add_tcPr()
        tc_mar = tc_pr.first_child_found_in("w:tcMar")
        if tc_mar is None:
            tc_mar = OxmlElement("w:tcMar")
            tc_pr.append(tc_mar)

        for margin, value in margins.items():
            node = tc_mar.find(qn(f"w:{margin}"))
            if node is None:
                node = OxmlElement(f"w:{margin}")
                tc_mar.append(node)
            node.set(qn("w:w"), str(value))
            node.set(qn("w:type"), "dxa")


def _clean_text(value: Any) -> str:
    if value is None:
        return ""
    text = str(value)
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", "", text)
    return text.strip()


def _split_paragraphs(text: str) -> list[str]:
    text = _clean_text(text)
    if not text:
        return []
    return [part.strip() for part in re.split(r"\n{2,}", text) if part.strip()]


def _strip_markdown(text: str) -> str:
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    return text


def _extract_first_paragraph(markdown: str) -> str:
    for part in _split_paragraphs(_strip_markdown(markdown)):
        if not part.startswith("#"):
            return part
    return ""


def _fmt_score(value: Any) -> str:
    if value is None or value == "":
        return "-"
    try:
        number = float(value)
        return f"{number:.1f}".rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return _clean_text(value)


def _fmt_percent(value: Any) -> str:
    if value is None or value == "":
        return "-"
    try:
        number = float(value)
        if number <= 1:
            number *= 100
        return f"{number:.0f}%"
    except (TypeError, ValueError):
        return _clean_text(value)


def _subgraph_summary(report: dict[str, Any]) -> str:
    subgraph = report.get("subgraph_summary") or {}
    node_count = subgraph.get("node_count", 0)
    edge_count = subgraph.get("edge_count", 0)
    return f"{node_count} 个节点 / {edge_count} 条关系"


def _make_report_id() -> str:
    return f"WIND-RPT-{datetime.now():%Y%m%d-%H%M%S}"


def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
